collections:
  authors:
   output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "categoriesstyle"
  - scope:
      path: ""
    values:
      layout: "default"   
  

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-archives

include: [categories]  

title: Industries of Inferno
description: Uncanny musings
author: Athotep Nyarl

relative_permalinks: false